name = "Portafolio personal"

build = "python -m pip install --user poetry && poetry install"
command = "poetry run reflex build && reflex serve"

port = "8081"

env = {
  "REFLEX_ENV": "production"
}

[build.environment]
  PYTHONPATH = "."

[context.production]
  build = "poetry run reflex build --prod"
  command = "poetry run reflex serve --prod"